# Generated by Django 2.2.4 on 2020-03-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_username', models.CharField(max_length=20)),
                ('ad_password', models.CharField(max_length=20)),
            ],
        ),
    ]
