# Generated by Django 2.2.4 on 2020-03-31 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_diseasemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicalmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=20)),
                ('med_desp', models.CharField(max_length=100)),
                ('des_med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.diseasemodel')),
            ],
        ),
    ]
