# Generated by Django 2.2.4 on 2020-03-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_medicalmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicalmodels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_name', models.CharField(max_length=20)),
                ('sysm', models.CharField(max_length=50)),
                ('med_name', models.CharField(max_length=20)),
                ('med_desp', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='medicalmodel',
        ),
    ]
